destigmatising mistakes post
skybet/skybet.github.io pull request #317
Opened 2021-08-02 16:27 UTC by MartinBlackburn

2021-08-02 17:06 UTC, cmbuckley requested changes

2021-08-02 17:06 UTC, cmbuckley commented on _posts/2021-08-02-destigmatising-mistakes-game-launch-incident-review.md
> +We looked at the overall release and worked out what changed around what we thought was causing the error, which thankfully we were right.
```suggestion
We looked at the overall release and worked out what changed around what we thought was causing the error, and thankfully we were right.
```

2021-08-02 17:06 UTC, cmbuckley commented on _posts/2021-08-02-destigmatising-mistakes-game-launch-incident-review.md
> +-   Having a larger time before merging out release into master, making rolling back easier.
```suggestion
-   Having a larger time before merging our release candidate into master, making rolling back easier.
```

2021-08-03 10:03 UTC, MartinBlackburn reviewed
looks good to me, thanks

2021-08-03 10:33 UTC, merged